#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
REMOTE_USER = "ubuntu"
REMOTE_HOST = "8.8.8.8"
SSH_KEY ="~/.ssh/school"

ssh -i "$SSH_KEY" "$REMOTE_USER@$REMOTE_HOST"
