#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
REMOTE_USER = "ubuntu"
REMOTE_HOST = "52.70.41.148"
SSH_KEY ="~/.ssh/school"

ssh -i ~/.ssh/school "$REMOTE_USER@$REMOTE_HOST"
