#!/usr/bin/env bash
#A Bash script that creates an RSA key pair.

# Define variables
KEY_NAME="school"
KEY_PATH="$HOME/.ssh/$KEY_NAME"
PASSPHRASE="betty"

# Ensure the .ssh directory exists
mkdir -p "$HOME/.ssh"

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f "$KEY_PATH" -N "$PASSPHRASE"
