#!/usr/bin/env bash
#A Bash script that creates an RSA key pair.

# Define variables
SAVE_FILE_NAME="$HOME/.ssh/school"
PASSPHRASE="betty"

# Ensure the .ssh directory exists
mkdir -p "$HOME/.ssh"

# Generate the RSA key pair
ssh-keygen -b 4096 -f "$SAVE_FILE_NAME" -N "$PASSPHRASE"
