#!/usr/bin/env bash
#SSH configuration file creation

Host 6373-web-01
    HostName 52.70.41.148
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    PubkeyAuthentication yes
    IdentitiesOnly yes

# Now, use the custom SSH configuration file for connection
ssh -F ~/.ssh/config ubuntu@52.70.41.148

# Append the public key to the authorized_keys file
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDfkHY8eBOwXjnwEBWeqC00yUIIaL0m0BkLabZ7bqMu9jBEHMVO6BsFJ9mo3Qg55qDWJOSFpMoxcNrpLIdcftx07kxR1BLlr7/NTrn7gUYHq7eYjKG1Nlar5+vyGnBs+7aE8LZ9k6115q672l5LvtcPvo7++wROWJATbNUUoX5KzzBSn+pekZANhHCEYsp+d99965Mqsv1Yw8c/7Ot9kiSoRilsJL37qtCy0HkB2RtGsqf2iX9aJvKp32MnfFIz9EOJHOIIJIwSKKqTRUpIZi0sdqGDicHlkwVvNxeHsB2oW82jvgnJY2w244eT7nOsExsa0b9GwJhb+6GaAiISGLbgiFK0n13Ss9wlfa3Bh6zyK4JpPxqrMTOvERQxKdwCR/kGiHW2qDz+0UmOxvIQtsV7XliIJx0l1/eyoh11W/7J6Txa+b0kRPLBtb+sZSCDWj23kh8qHUPix0buMXBIwFieOdQuN3oSYj4LoFilc+YGgKNAd/l7ln/qP9DIbPzS/XgXKMeup42JjGQou0My8iKEPd4mT/hlDr7EjhP12bQ5d9CAOPLXy4FKRH9AFGGsKg5FLmd1XQ5hVbPkxdXFGPX0YfYQ/WmDXFZNytxnTQoVUdu9hI3spxjecINbY/9PfAP6nod5PHs0XGJn2LwofO9HpYgyInEsER+CGS40A2sZxw== root@7b33c1707068" >> ~/.ssh/authorized_keys

# Ensure correct permissions
chmod 600 ~/.ssh/authorized_keys
chmod 700 ~/.ssh
