#!/usr/bin/env bash
#SSH configuration file creation

Host web01
    HostName 98.98.98.98
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    PubkeyAuthentication yes
    IdentitiesOnly yes
