#!/usr/bin/env bash
# Make Nginx is running as the nginx user

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed."
    exit 1
fi

# Update the Nginx configuration file to run as the nginx user and listen on port 8080
NGINX_CONF="/etc/nginx/nginx.conf"

# Make a backup of the original configuration file
sudo cp "$NGINX_CONF" "${NGINX_CONF}.bak"

# Update user to nginx and listen on port 8080
sudo sed -i 's/user www-data/user nginx' "$NGINX_CONF"
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Ensure that the nginx user exists
if ! id -u nginx &> /dev/null; then
    echo "Creating nginx user..."
    sudo useradd -r -s /sbin/nologin nginx
fi

sudo chmod 644 "$NGINX_CONF"

# Restart Nginx to apply changes
sudo -u nginx service nginx restart
