#!/usr/bin/env bash
# Creation and configuration of the second server

# Exit if any command fails
set -e

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP header in the correct Nginx configuration
CONFIG_FILE="/etc/nginx/sites-available/default"

# Ensure the directive is inside the 'server' block
header_str="server_name _;\\n    add_header X-Served-By $(hostname);"
sudo sed -i "s|server_name _;|$header_str|" "$CONFIG_FILE"

# Test and reload Nginx
sudo nginx -t
sudo service nginx restart
