#!/usr/bin/env bash
#find out what's keeping my Ubuntu container's Nginx installation from listening on port 80
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pis
